#ifndef __STARTUP__H
#define __STARTUP__H

void Default_Handler(void);
/* Interrupt Vector Handlers*/
void Reset_Handler(void);
void NMI_Handler(void) __attribute__((weak, alias("Default_Handler")));
void HardFault_Handler(void) __attribute__((weak, alias("Default_Handler")));
void MemManage_Handler(void) __attribute__((weak, alias("Default_Handler")));
void BusFault_Handler(void) __attribute__((weak, alias("Default_Handler")));
void UsageFault_Handler(void) __attribute__((weak, alias("Default_Handler")));
void SVCall_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Debug_Handler(void) __attribute__((weak, alias("Default_Handler")));
void PendSV_Handler(void) __attribute__((weak, alias("Default_Handler")));
void SysTick_Handler(void) __attribute__((weak, alias("Default_Handler")));
void GPIOPortA_Handler(void) __attribute__((weak, alias("Default_Handler")));
void GPIOPortB_Handler(void) __attribute__((weak, alias("Default_Handler")));
void GPIOPortC_Handler(void) __attribute__((weak, alias("Default_Handler")));
void GPIOPortD_Handler(void) __attribute__((weak, alias("Default_Handler")));
void GPIOPortE_Handler(void) __attribute__((weak, alias("Default_Handler")));
void UART0_Handler(void) __attribute__((weak, alias("Default_Handler")));
void UART1_Handler(void) __attribute__((weak, alias("Default_Handler")));
void SSI0_Handler(void) __attribute__((weak, alias("Default_Handler")));
void I2C0_Handler(void) __attribute__((weak, alias("Default_Handler")));
void PWM0Fault_Handler(void) __attribute__((weak, alias("Default_Handler")));
void PWM0Generator0_Handler(void) __attribute__((weak, alias("Default_Handler")));
void PWM0Generator1_Handler(void) __attribute__((weak, alias("Default_Handler")));
void PWM0Generator2_Handler(void) __attribute__((weak, alias("Default_Handler")));
void QEI0_Handler(void) __attribute__((weak, alias("Default_Handler")));
void ADC0Sequence0_Handler(void) __attribute__((weak, alias("Default_Handler")));
void ADC0Sequence1_Handler(void) __attribute__((weak, alias("Default_Handler")));
void ADC0Sequence2_Handler(void) __attribute__((weak, alias("Default_Handler")));
void ADC0Sequence3_Handler(void) __attribute__((weak, alias("Default_Handler")));
void WatchdogTimer01_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer0A_16_32_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer0B_16_32_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer1A_16_32_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer1B_16_32_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer2A_16_32_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer2B_16_32_Handler(void) __attribute__((weak, alias("Default_Handler")));
void AnalogComparator0_Handler(void) __attribute__((weak, alias("Default_Handler")));
void AnalogComparator1_Handler(void) __attribute__((weak, alias("Default_Handler")));
void SystemControl_Handler(void) __attribute__((weak, alias("Default_Handler")));
void FlashMemoryControl_Handler(void) __attribute__((weak, alias("Default_Handler")));
void GPIOPortF_Handler(void) __attribute__((weak, alias("Default_Handler")));
void UART2_Handler(void) __attribute__((weak, alias("Default_Handler")));
void SSI1_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer3A_16_32_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer3B_16_32_Handler(void) __attribute__((weak, alias("Default_Handler")));
void I2C1_Handler(void) __attribute__((weak, alias("Default_Handler")));
void QEI1_Handler(void) __attribute__((weak, alias("Default_Handler")));
void CAN0_Handler(void) __attribute__((weak, alias("Default_Handler")));
void CAN1_Handler(void) __attribute__((weak, alias("Default_Handler")));

void HibernationModule_Handler(void) __attribute__((weak, alias("Default_Handler")));
void USB_Handler(void) __attribute__((weak, alias("Default_Handler")));
void PWM0Generator3_Handler(void) __attribute__((weak, alias("Default_Handler")));
void DMASoftware_Handler(void) __attribute__((weak, alias("Default_Handler")));
void DMAError_Handler(void) __attribute__((weak, alias("Default_Handler")));
void ADC1Sequence0_Handler(void) __attribute__((weak, alias("Default_Handler")));
void ADC1Sequence1_Handler(void) __attribute__((weak, alias("Default_Handler")));
void ADC1Sequence2_Handler(void) __attribute__((weak, alias("Default_Handler")));
void ADC1Sequence3_Handler(void) __attribute__((weak, alias("Default_Handler")));
void SSI2_Handler(void) __attribute__((weak, alias("Default_Handler")));
void SSI3_Handler(void) __attribute__((weak, alias("Default_Handler")));
void UART3_Handler(void) __attribute__((weak, alias("Default_Handler")));
void UART4_Handler(void) __attribute__((weak, alias("Default_Handler")));
void UART5_Handler(void) __attribute__((weak, alias("Default_Handler")));
void UART6_Handler(void) __attribute__((weak, alias("Default_Handler")));
void UART7_Handler(void) __attribute__((weak, alias("Default_Handler")));
void I2C2_Handler(void) __attribute__((weak, alias("Default_Handler")));
void I2C3_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer4A_16_32_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer4B_16_32_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer5A_16_32_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer5B_16_32_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer0A_32_64_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer0B_32_64_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer1A_32_64_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer1B_32_64_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer2A_32_64_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer2B_32_64_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer3A_32_64_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer3B_32_64_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer4A_32_64_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer4B_32_64_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer5A_32_64_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Timer5B_32_64_Handler(void) __attribute__((weak, alias("Default_Handler")));
void SystemException_Handler(void) __attribute__((weak, alias("Default_Handler")));
void PWM1Generator0_Handler(void) __attribute__((weak, alias("Default_Handler")));
void PWM1Generator1_Handler(void) __attribute__((weak, alias("Default_Handler")));
void PWM1Generator2_Handler(void) __attribute__((weak, alias("Default_Handler")));
void PWM1Generator3_Handler(void) __attribute__((weak, alias("Default_Handler")));
void PWM1Fault_Handler(void) __attribute__((weak, alias("Default_Handler")));
/* Interrupt Vector Handlers End*/

void init_data(uint32_t *dst_start, uint32_t *dst_end, uint32_t *src);
void init_bss(uint32_t *start, uint32_t *end);
#endif
