#ifndef __STARTUP__H
#define __STARTUP__H

void Default_Handler(void);
/* Interrupt Vector Handlers*/
void Reset_Handler(void);
void NMI_Handler(void) __attribute__((weak, alias("Default_Handler")));
void HardFault_Handler(void) __attribute__((weak, alias("Default_Handler")));
void MemManage_Handler(void) __attribute__((weak, alias("Default_Handler")));
void BusFault_Handler(void) __attribute__((weak, alias("Default_Handler")));
void UsageFault_Handler(void) __attribute__((weak, alias("Default_Handler")));
void SVCall_Handler(void) __attribute__((weak, alias("Default_Handler")));
void Debug_Handler(void) __attribute__((weak, alias("Default_Handler")));
void PendSV_Handler(void) __attribute__((weak, alias("Default_Handler")));
void SysTick_Handler(void) __attribute__((weak, alias("Default_Handler")));
void DMA0_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DMA1_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DMA2_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DMA3_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DMA4_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DMA5_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DMA6_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DMA7_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DMA8_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DMA9_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DMA10_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DMA11_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DMA12_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DMA13_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DMA14_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DMA15_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DMA_Error_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void MCM_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void FTFE_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void Read_Collision_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void LVD_LVW_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void LLW_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void Watchdog_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void RNG_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void I2C0_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void I2C1_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void SPI0_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void SPI1_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void I2S0_Tx_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void I2S0_Rx_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void UART0_LON_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void UART0_RX_TX_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void UART0_ERR_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void UART1_RX_TX_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void UART1_ERR_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void UART2_RX_TX_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void UART2_ERR_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void UART3_RX_TX_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void UART3_ERR_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void ADC0_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void CMP0_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void CMP1_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void FTM0_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void FTM1_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void FTM2_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void CMT_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void RTC_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void RTC_Seconds_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void PIT0_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void PIT1_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void PIT2_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void PIT3_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void PDB0_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void USB0_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void USBDCD_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void Reserved71_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DAC0_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void MCG_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void LPTimer_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void PORTA_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void PORTB_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void PORTC_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void PORTD_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void PORTE_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void SWI_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void SPI2_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void UART4_RX_TX_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void UART4_ERR_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void UART5_RX_TX_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void UART5_ERR_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void CMP2_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void FTM3_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void DAC1_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void ADC1_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void I2C2_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void CAN0_ORed_Message_buffer_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void CAN0_Bus_Off_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void CAN0_Error_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void CAN0_Tx_Warning_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void CAN0_Rx_Warning_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void CAN0_Wake_Up_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void SDHC_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void ENET_1588_Timer_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void ENET_Transmit_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void ENET_Receive_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
void ENET_Error_IRQHandler(void) __attribute__((weak, alias("Default_Handler")));
/* Interrupt Vector Handlers End*/

void init_data(uint32_t *dst_start, uint32_t *dst_end, uint32_t *src);
void init_bss(uint32_t *start, uint32_t *end);
#endif
